default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: opis
  password: Dfr368qE
  host: localhost

development:
  <<: *default
  database: OpisP21_development

test:
  <<: *default
  database: OpisP21_test

production:
  <<: *default
  database: OpisP21_production
  username: OpisP21
  password: <%= ENV['OPISP1_DATABASE_PASSWORD'] %>
